Month 8/step 2
Varikash/stellar-burger pull request #4
Opened 2023-04-23 01:08 UTC by Varikash

Month 8/step 2

2023-04-23 01:39 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Отличная организация хранилища
- Правильное использование Redux Toolkit
- Нельзя сделать пустой заказ
- Отлично реализован `Dnd` 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У нескольких компонентов не хватает `propTypes`
- если экшен не выполняет сайдэффектов, то не должна диспатчится функция и пропускатсья через `thunk`
- при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-23 01:39 UTC, andryxxa93 commented on src/components/App/App.jsx
> +  const { loadingIngredients, errorLoadingIngredients, ingredientsLoaded} = useSelector(store => store.ingredients);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-23 01:39 UTC, andryxxa93 commented on src/components/IngredientElement/IngredientElement.jsx
> +const IngredientElement = ({index, item}) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-04-23 01:39 UTC, andryxxa93 commented on src/services/actions/fetchOrder.js
> +export const clearOrder = () => (dispatch) => {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-04-23 01:39 UTC, andryxxa93 commented on src/services/reducers/burgerConstructionSlice.js
> +      const key = uuidv4();
**Надо исправить**

редьюсер должен быть чистой функции, сейчас при каждом вызове добавления ингредиента результат будет отличаться, даже если стейт и экшен одинаковые - будет генерироваться каждый раз новый id,  при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене, а не генерировать в редьюсере. Иначе это делает редьюсер не чистой функцией, что нарушает правило редьюсеров

2023-04-23 01:39 UTC, andryxxa93 commented on src/services/actions/fetchIngredients.js
> +      getIngredients()
**Можно лучше**

здесь и в других усилителях следует делать return промиса, что нам поможет при тестировании в следующем спринте и при необходимости можно будет продолжить цепочку в компоненте и совершить действие после выполнения запроса

т.е. должно быть:
```
export const getIngredients = () => (dispatch) => {
	dispatch({ type: GET_INGREDIENTS_REQUEST });

	return fetch(`${API_URL}ingredients`)   //return  промиса
        .................
```

проверьте и в других похожих местах

2023-04-23 15:39 UTC, Varikash commented on src/components/App/App.jsx
> +  const { loadingIngredients, errorLoadingIngredients, ingredientsLoaded} = useSelector(store => store.ingredients);
Переделал.

2023-04-23 15:39 UTC, Varikash commented on src/components/IngredientElement/IngredientElement.jsx
> +const IngredientElement = ({index, item}) => {
Добавил.

2023-04-23 15:43 UTC, Varikash commented on src/services/actions/fetchIngredients.js
> +      getIngredients()
Не совсем понял что имеется в виду. Сейчас у меня диспатчится GET_FEED до начала запроса. Отдельный запрос я добавил в функцию getIngredients, там fetch возвращается, само собой, иначе функция бы не работала. Все остальные диспатчи идут следом. Вы предлагаете по сути то же самое, только местами поменять пару строк когда. В чем смысл?

2023-04-23 15:53 UTC, Varikash commented on src/services/actions/fetchOrder.js
> +export const clearOrder = () => (dispatch) => {
Исправил.

2023-04-23 16:30 UTC, Varikash commented on src/services/reducers/burgerConstructionSlice.js
> +      const key = uuidv4();
Исправлено

2023-04-24 06:09 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-24 15:42 UTC, merged